name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  credo:
    name: Credo
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:
      - name: Set up Elixir and OTP
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.11'
          otp-version: '23.2'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Restore cache for deps/ and _build/ directories'
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Run credo
        run: mix credo
